damzi/urls.py
from django.urls import path
from . import views


app_name = 'damzi'

urlpatterns = [
	path('', views.index, name='index'),
	path('messages/get/', views.get_messages, name='get_messages'),
]

library/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from .import views

app_name = 'library'

urlpatterns = [
    path('courses/', views.list_courses, name='list_courses'),
    path('course/<uuid:pk>/topics/', login_required(views.list_topics), name='list_topics'),
    path('course/topic/<uuid:pk>/sub-topics/', views.list_subtopics, name='list_subtopics'),
    path('course/topic/sub-topic/<uuid:pk>/content/', views.list_subtopic_content, name='list_subtopic_content'),
    path('topic/<uuid:pk>/', login_required(views.topic_detail), name='topic_detail'),
    path('course/selection/add/', views.add_course_selection, name='add_course_selection'),
    path('course/selection/remove/', views.remove_course_selection, name='remove_course_selection'),
    path('faq/', views.faq, name='faq'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),

    # special urlpatterns
    path('comment_app/load/<topic_id>/', views.load_comment_app, name='load_comment_app'),
]

library/models.py
import os
import uuid

from ckeditor_uploader.fields import RichTextUploadingField
from django.core.exceptions import ValidationError
from django.db import models
from django.dispatch import receiver
from django.utils import timezone


class Institution(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=100)

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return self.name


class School(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    institution = models.ForeignKey(Institution, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return self.name


class Department(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    school = models.ForeignKey(School, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return self.name


class Course(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    institution = models.ForeignKey(Institution, null=True, on_delete=models.CASCADE, editable=False)
    department = models.ForeignKey(Department, blank=True, null=True, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    code = models.CharField(max_length=100)
    is_required = models.BooleanField(default=False, editable=False)

    def save(self, *args, **kwargs):
        if self.department is None:
            self.is_required = True
        super().save(*args, **kwargs)

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return self.code + ":" + self.name


class Topic(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)

    prev = models.OneToOneField('self', null=True, blank=True, verbose_name='previous topic',
                                on_delete=models.DO_NOTHING, related_name='next')



    @classmethod
    def get_topics_as_list(cls, course):
        try:
            first_topic = cls.objects.get(course=course, prev__isnull=True)
        except cls.DoesNotExist:
            return []
        topics = [first_topic]
        try:
            while topics[-1].next:
                topics.append(topics[-1].next)
        except Topic.next.RelatedObjectDoesNotExist:
            return topics

    def __str__(self):
        return self.title


class SubTopic(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    content = RichTextUploadingField(editable=False, null=True)
    temp_content = RichTextUploadingField(verbose_name='content')
    push_updates = models.BooleanField(default=False)

    prev = models.OneToOneField('self', null=True, blank=True, verbose_name='previous subtopic',
                                on_delete=models.DO_NOTHING, related_name='next')

    @classmethod
    def get_subtopics_as_list(cls, topic):
        try:
            first_subtopic = cls.objects.get(topic=topic, prev__isnull=True)
        except cls.DoesNotExist:
            return []
        subtopics = [first_subtopic]
        try:
            while subtopics[-1].next:
                subtopics.append(subtopics[-1].next)
        except cls.next.RelatedObjectDoesNotExist:
            return subtopics

    def __str__(self):
        return self.title


class Comment(models.Model):
    from accounts.models import User

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE, editable=False)
    commenter = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.TextField()
    date_uploaded = models.DateTimeField(editable=False, default=timezone.now)
    is_approved = models.BooleanField(verbose_name='check to approve', default=False)

    def __str__(self):
        return self.commenter.username


class Reply(models.Model):
    from accounts.models import User

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    comment = models.ForeignKey(
        Comment,
        on_delete=models.CASCADE,
        limit_choices_to={'is_approved': True}
    )
    replier = models.ForeignKey(User, on_delete=models.CASCADE)
    reply = models.TextField()
    date_uploaded = models.DateTimeField(editable=False, default=timezone.now)


class CourseSelection(models.Model):
    from accounts.models import User

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    semester = models.IntegerField(choices=((1, 2,),), default=os.environ.get('SEMESTER', 2))
    selection_date = models.DateTimeField(auto_now_add=True)


@receiver(models.signals.post_save, sender=SubTopic)
def push_updates(sender, instance, **kwargs):
    if instance.push_updates:
        instance.content = instance.temp_content
        instance.push_updates = False
        instance.save()

library/forms.py
from django import forms
from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('comment',)

library/views.py
import json

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.http import HttpResponse
from django.shortcuts import render_to_response, get_object_or_404, render, redirect

from accounts.models import User
from accounts.utils import get_user
from .forms import CommentForm
from .models import Topic, Course, Department, Comment, CourseSelection, SubTopic


# def department_list(request):
#     departments = Department.objects.all()
#     context = {
#         'departments': departments
#     }
#     return render(request, 'library/department.html', context)


def list_courses(request):
    required_courses = Course.objects.filter(is_required=True)
    departments = Department.objects.all()
    course_selections = CourseSelection.objects.filter(user=get_user(request))
    selected_courses = {course_selection.course for course_selection in course_selections}

    paginator = Paginator(departments, 8)

    page = request.GET.get('page')
    departments = paginator.get_page(page)

    context = {
        'required_courses': required_courses,
        'departments': departments,
        'selected_courses': selected_courses,
    }
    return render(request, 'library/courses.html', context)


# @login_required
# def department_courses(request, pk):
#     department = get_object_or_404(Department,id=pk)
#     context = {
#         'courses': department.course_set.all()
#     }
#     return render(request, 'library/course.html', context)


@login_required
def list_topics(request, pk):
    course = get_object_or_404(Course, id=pk)
    topics = Topic.get_topics_as_list(course)

    context = {
        'topics': topics,
    }
    return render(request, 'library/list_topics.html', context)


@login_required
def list_subtopics(request, pk):
    topic = get_object_or_404(Topic, id=pk)
    subtopics = SubTopic.get_subtopics_as_list(topic)
    context = {
        'topic': topic,
        'subtopics': subtopics,
    }
    return render(request, 'library/list_subtopics.html', context)


@login_required
def list_subtopic_content(request, pk):
    subtopic = get_object_or_404(SubTopic, id=pk)

    context = {
        'subtopic': subtopic
    }
    return render(request, 'library/list_subtopic_content.html', context)


@login_required
def topic_detail(request, pk):
    topic = get_object_or_404(Topic, id=pk)
    profile_picture = get_object_or_404(User, id=request.user.id).profile.profile_picture
    comment_list = Comment.objects.filter(topic__id=pk, is_approved=False).order_by('-date_uploaded')

    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            # new_comment = Comment()
            new_comment.commenter = request.user
            new_comment.topic = topic
            # new_comment.comment = comment_form.cleaned_data['comment']
            new_comment.save()
            # success_msg = 'Thanks for learning smart with damzinium. We appreciate your feedback.'
            return redirect('library:topic_detail', pk=pk)
        else:
            return redirect('library:topic_detail', pk=pk)
    else:
        comment_form = CommentForm
        context = {
            'comment_form': comment_form,
            'comment_list': comment_list,
            'topic': topic,
            'profile_picture': profile_picture,
        }
        return render(request, 'library/topic_detail.html', context)


def faq(request):
    return render_to_response('library/faq.html')


def about(request):
    return render_to_response('library/about.html')


def contact(request):
    return render_to_response('library/contact.html')


@login_required
def add_course_selection(request):
    if request.is_ajax() and request.method == 'POST':
        already_selected = False
        course_id = request.POST.get('course_id')
        user = get_user(request)
        course = get_object_or_404(Course, id=course_id)
        course_selections = CourseSelection.objects.filter(user=user)
        for course_selection in course_selections:
            if course == course_selection.course:
                already_selected = True
                break
        if not already_selected:
            new_course_selection = CourseSelection()
            new_course_selection.user = user
            new_course_selection.course = course
            new_course_selection.save()
            messages.success(request, 'Successfully added course to your selections.')
            response_obj = {
                'status': 'success',
                'course_id': course_id,
            }
        else:
            messages.error(request, 'You have already selected this course.')
            response_obj = {
                'status': 'error',
            }
    else:
        messages.error(request, 'Could not add course to your selections. Please try again.')
        response_obj = {
            'status': 'error',
        }
    response_json = json.dumps(response_obj)
    return HttpResponse(response_json, content_type='text/json')


@login_required
def remove_course_selection(request):
    if request.is_ajax() and request.method == 'POST':
        user = get_user(request)
        course = get_object_or_404(Course, id=request.POST.get('course_id'))
        course_selection = CourseSelection.objects.get(user=user, course=course)
        course_selection.delete()
        messages.success(request, 'Successfully remove course from your selection.')
        response_obj = {
            'status': 'success',
            'course_id': request.POST.get('course_id'),
        }
    else:
        messages.error(request, 'Could not add course to your selections. Please try again.')
        response_obj = {
            'status': 'error',
        }
    response_json = json.dumps(response_obj)
    return HttpResponse(response_json, content_type='text/json')


@login_required
def load_comment_app(request, topic_id):
    if request.is_ajax() and request.method == 'GET':
        comments = Comment.objects.filter(topic__id=topic_id)
        context = {
            'topic_id': topic_id,
            'comments': comments,
        }
        return render(request, 'library/comment_app.html', context)

library/templates/library/comment_app.html
<form action="" method="post">
    <textarea name="comment" id="id_comment">
    </textarea>
    <button type="submit" id="comment-post-btn">Post</button>
</form>
<ul class="comments">
    {% for comment in comments %}
        <li>
            {% if comment.commenter.profile.profile_picture %}
                <img src="{{ comment.commenter.profile.profile_picture }}"/>
            {% else %}
                <img src="/static/account/images/user.jpg"/>
            {% endif %}
            {{ comment.commenter }}
            {{ comment.comment }}
            {{ comment.date_uploaded }}
            <ul class="replies">
                {% for reply in comment.reply_set.all %}
                    <li>
                        
                        {{ reply.replier }}
                        {{ reply.reply }}
                    </li>
                {% endfor %}
            </ul>
        </li>
    {% endfor %}
</ul>
<script>
    const defaultProfilePictureURL = '/static/account/images/user.jpg';
    let commentSocket = new WebSocket(
        'ws://' + window.location.host + '/ws/library/comment/' + '{{ topic_id }}/'
    );
    commentSocket.onmessage = function (e) {
        let commentData = JSON.parse(e.data);
        console.log(commentData);
        let newCommentDOMObject = '';
        newCommentDOMObject += '<li>';
        let profilePictureURL = commentData['profile_picture'];
        if(profilePictureURL === '') {
            profilePictureURL = defaultProfilePictureURL;
        }
        newCommentDOMObject += '<img src="' + profilePictureURL + '"/>';
        newCommentDOMObject += commentData['username'];
        newCommentDOMObject += commentData['comment'];
        newCommentDOMObject += commentData['date_uploaded'];
        newCommentDOMObject += '<ul class="replies"></ul>';
        console.log(e.data);
        console.log(newCommentDOMObject);
        $('.comments').append(newCommentDOMObject);
    };
    commentSocket.onclose = function () {
        console.error('comment socket closed');
    };
    $
    $('#id_comment').keydown(function (e) {
        if(e.keyCode === 13 && $('#id_comment').val() != '') {
            e.preventDefault();
            $('#comment-post-btn').click();
        }
    });
    $('#comment-post-btn').click(function (e) {
        e.preventDefault();
        let commentBoxDOMObject = $('#id_comment');
        let comment = commentBoxDOMObject.val();
        commentBoxDOMObject.val('');
        commentSocket.send(
            JSON.stringify(
                {
                    'topic_id': parseInt('{{ topic_id }}'),
                    'comment': comment,
            }));
    })
</script>

library/templates/library/course.html
<ul>
	{% for course in courses %}
	<ul>
		<li><a href="{% url 'library:detail' course.id %}">
			{{ course.course_name }}
		</a></li>
	</ul>
	{% endfor %}
</ul>

library/templates/library/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Study</title>
</head>
<body>
{% for topic in topics %}
    {# Each "topic" is a Topic model object. #}
    {{ topic.content|safe }}<br />
{% endfor %}

<div class="pagination">
    <span class="step-links">
        {% if theposts.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ theposts.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ theposts.number }} of {{ theposts.paginator.num_pages }}.
        </span>

        {% if theposts.has_next %}
            <a href="?page={{ theposts.next_page_number }}">next</a>
            <a href="?page={{ theposts.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>
</body>
</html>

library/templates/library/list_subtopic_content.html
{%  extends 'library/base.html' %}
{% load static %}
{% load humanize %}

{% block modal %}
<!-- Modal -->
<div class="modal fade" id="studymenu" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <!--Content-->
        <div class="modal-content">
            <!--Header-->
            <div class="modal-header">
                <h4 class="modal-title w-100 red-text" id="myModalLabel">Related Topics</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <!--Body-->
            <div class="modal-body">
                <ul class="list-group z-depth-0">
                    {% for topic in topic.course.topic_set.all %}
                        <li class="list-group-item justify-content-between grey-text">
                            <a href="{% url 'library:topic_detail' topic.id %}">{{ topic.title }} ...</a>
                        </li>
                            {% endfor %}
                        <!--<li class="list-group-item justify-content-between grey-text">
                            <a href="#">{ { topic.title }}</a>
                        </li>-->
                </ul>
            </div>
            <!--Footer-->
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
        <!--/.Content-->
    </div>
</div>
<!-- Modal -->
{% endblock %}

{% block content %}
<div class="container-fluid">
    <!--RESTRUCTURING-->
    <div class="row">
        <!--LEFT-->
        <div class="col-md">
            <!--mini nav-->
            <nav class="navbar navbar-expand-md navbar-dark success-color no-content mt-4 mb-4">
        <!-- SideNav slide-out2 button -->
        <div class="float-left">
            <a class="white-text" data-toggle="modal" data-target="#studymenu">
                <i class="fa fa-bars"></i>
            </a>
        </div>

        <!--Breadcrumb-->
        <div class="light-font">
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a class="white-text" href="{% url 'library:list_courses' %}">Courses</a>
                </li>
                <!--add department name-->
                <!--<li class="breadcrumb-item"><a class="white-text" href="#">{ { department.department_name }}</a>-->
                <li class="breadcrumb-item active white-text">{{ topic.course_name }}</li>
            </ol>
        </div>

        <!--configure NEXT and PREVIOUS functionality. Using Django Pagination-->
        <ul class="navbar-nav ml-auto nav-flex-icons">
            <li class="nav-item">
                {% if subtopic.prev %}
                <a href="{% url 'library:list_subtopic_content' subtopic.prev.pk %}" class="nav-link">Previous</a>
                {% else %}
                <a href="" class="nav-link disabled">Previous</a>
                {% endif %}
            </li>
            <li class="nav-item">
                {% if subtopic.next %}
                <a href="{% url 'library:list_subtopic_content' subtopic.next.pk %}" class="nav-link">Next</a>
                {% else %}
                <a href="" class="nav-link disabled">Next</a>
                {% endif %}
            </li>
        </ul>
    </nav>
            <!--/mini nav-->

            <!--topic content-->
            <div class="card mb-4">
                <div class="card-header deep-orange lighten-1 white-text">
                    {{ subtopic.title }}
                </div>
                <div class="card-body">
                    <div class="card-text">{{ subtopic.content|safe }}</div>
                </div>
            </div>
            <!--/topic content-->

            <!--original comment box-->
            <div class="card" id="comment-section">
                <div class="card-body">
                    <h4 class="card-title">Let's hear your thoughts...</h4>
                    <!-- styling in style.css -->
                    <form action="" method="post" id="comment-form">
                        {% csrf_token %}
                        {% if profile_picture %}
                        <img src="{{ profile_picture.url }}" class="profile-picture-small"/>
                        {% else %}
                        <img src="{% static 'account/images/default.jpg' %}" class="profile-picture-small"/>
                        {% endif %}
                        {% for field in comment_form %}
                        {{ field }}
                        {% endfor %}
                        <button type="submit" id="submit-comment" class="btn btn-secondary">Comment</button>
                    </form>
                    <hr/>
                    <div>
                            {% if comment_list %}
                            <ul id="comment-list">
                                {% for comment in comment_list %}
                                <li>
                                    <table>
                                        <tbody>
                                        <tr>
                                            <td rowspan="2">
                                                {% if comment.commenter.profile.profile_picture %}
                                                <img src="{{ comment.commenter.profile.profile_picture.url }}" class="profile-picture-small"/>
                                                {% else %}
                                                <img src="{% static 'account/images/default.jpg' %}" class="profile-picture-small"/>
                                                {% endif %}
                                            </td>
                                            <td>
                                                {{ comment.commenter }}
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                {{ comment.date_uploaded|naturaltime }}
                                            </td>
                                        </tr>
                                        <tr>
                                            <td colspan="2">
                                                {{ comment.comment }}
                                            </td>
                                        </tr>
                                        </tbody>
                                    </table>
                                    {% if comment.reply_set %}
                                    <ul id="reply-list">
                                        {% for reply in comment.reply_set.all %}
                                        <li>
                                            <table>
                                                <tbody>
                                                <tr>
                                                    <td rowspan="2">
                                                        {% if reply.replier.profile.profile_picture %}
                                                        <img src="{{ reply.replier.profile.profile_picture.url }}" class="profile-picture-small"/>
                                                        {% else %}
                                                        <img src="{% static 'account/images/default.jpg' %}" class="profile-picture-small"/>
                                                        {% endif %}
                                                    </td>
                                                    <td>
                                                        {{ reply.replier }}
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        {{ reply.date_uploaded|timesince }} ago                                                                                            </td>
                                                </tr>
                                                <tr>
                                                    <td colspan="2">
                                                        {{ reply.reply }}
                                                    </td>
                                                </tr>
                                                </tbody>
                                            </table>
                                        </li>
                                        {% endfor %}
                                    </ul>
                                    {% endif %}
                                    {% endfor %}
                            </ul>
                            {% else %}
                            <div class="text-center text-muted">
                                <i>Be the first to comment.</i>
                            </div>
                            {% endif %}
                        </div>
                </div>
            </div>
            <!--/original comment box-->
        </div>

        <!--RIGHT-->
        <div class="col-md-4 mt-4" style="height: 100%; z-index: 1;right:20px;">

            <div style="position:fixed; margin-right: 20px;">
                <!--Card-->
                <div class="card mb-2">
                    <!--Card content-->
                    <div class="card-body">
                        <!--Title-->
                        <h4 class="card-title">Card title</h4>
                        <!--Text-->
                        <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                    </div>
                </div>
                <!--/.Card-->
                <!--Card-->
                <div class="card mb-2">
                    <!--Card content-->
                    <div class="card-body">
                        <!--Title-->
                        <h4 class="card-title">Card title</h4>
                        <!--Text-->
                        <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                    </div>
                </div>
                <!--/.Card-->
                <!--Card-->
                <div class="card mb-2">
                    <!--Card content-->
                    <div class="card-body">
                        <!--Title-->
                        <h4 class="card-title">Card title</h4>
                        <!--Text-->
                        <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                    </div>
                </div>
                <!--/.Card-->
            </div>
        </div>
    </div>
</div>
{% endblock %}

library/templates/library/list_subtopics.html
<html>
<body>
    {% if topic.prev %}
        <a href="{% url 'library:list_subtopics' topic.prev.pk %}">Previous</a>
    {% else %}
        <a href="">Previous</a>
    {% endif %}

    {% if topic.next %}
        <a href="{% url 'library:list_subtopics' topic.next.pk %}">Next</a>
    {% else %}
        <a href="">Next</a>
    {% endif %}

    {% if subtopics %}
        {% for subtopic in subtopics %}
            <a href="{% url 'library:list_subtopic_content' subtopic.pk %}">{{ subtopic.title }}</a>
        {% endfor %}
    {% else %}
        No sub-topics
    {% endif %}
</body>
</html>

library/templates/library/list_topics.html
{% extends 'library/base.html' %}
{% load static %}

{% block title %}{{ course.code }}{% endblock %}

{% block content %}

<style type="text/css">
    .navigation {
        border: 1px solid red;
    }

    .pagination .page-link {
        font-size: 1.5rem !important;
    }
</style>

<!-- advertisement 1 -->
<!-- <div>
    <p class="text-center txt-ad-1"><a href="#">Vote for IA for UGSRC President 2019.</a></p>
</div> -->
<!-- advertisement 1 -->
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <center>
                <h3>List of topics</h3>
            </center>
            <!--course generator-->

            {% if topics %}
            {% for topic in topics %}
            <div class="card">
                <div class="card-header light-green darken-1 lighten-1 white-text">
                    {{ topic.course }}
                </div>
                <div class="card-body">
                    <h4 class="card-title">{{ topic.title }}</h4>
                    <a href="{% url 'library:list_subtopics' topic.pk %}" class="btn damzinium-green-head">SUB-TOPICS</a>
                </div>
            </div>
            <br/>
            {% endfor %}
            {% else %}
            No topics
            {% endif %}
            <!-- advertisement 1 -->
            <!-- <div>
                <p class="text-center txt-ad-1"><a href="#">Vote for IA for UGSRC President 2019.</a></p>
            </div> -->
            <!-- advertisement 1 -->
            <hr>
            <nav aria-label="Page navigation">
                <ul class="pagination pg-blue justify-content-center">
                    {% if topics.has_previous %}
                    <li class="page-item "><a href="?page=1" class="page-link">First&laquo;</a></li>
                    <li class="page-item "><a href="?page={{ topics.previous_page_number }}"
                            class="page-link">Previous&lsaquo;</a></li>
                    {% endif %}

                    <li class="page-item"><a class="page-link"> Page {{ topics.number }} of
                            {{ topics.paginator.num_pages }} </a> </li>

                    {% if topics.has_next %}
                    <li class="page-item "><a href="?page={{ topics.next_page_number }}"
                            class="page-link">Next&rsaquo;</a></li>
                    <li class="page-item "><a href="?page={{ topics.paginator.num_pages }}" class="page-link">Last&raquo;</a>
                    </li>
                    {% endif %}
                </ul>
            </nav>
            <hr>
        </div> <!-- /.col-12 -->
    </div> <!-- /.row -->
</div> <!-- /.container -->
{% endblock %}