accounts/urls.py
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required
from django.urls import path

from . import views

app_name = 'accounts'

urlpatterns = [
    path('', login_required(views.home), name='profile'),
    # path('ots/', login_required(views.OtsView.as_view()), name='ots'),
    path('ots/', login_required(views.ots), name='ots'),
    path('register/', views.UserRegistrationView.as_view(), name='register'),

    # user auth urls
    path('login/', views.ac_login, name='login'),
    path('logout/', views.ac_logout, name='logout'),
    # path('auth/', views.auth_view, name='auth_view'),

    # # ugrc
    # path('topic/<int:pk>/', (views.UgrcTopicView.as_view()), name='ugrc_detail'),
    # path('content/<int:pk>/', (views.UgContent.as_view()), name='content'),

    # password reset
    path('reset_password/', auth_views.PasswordResetView.as_view(success_url='password_reset_done'), name='password_reset'),
    path('reset_password/password_reset_done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset_password/password_reset_confirm/<slug:uidb64>/<slug:token>',
         auth_views.PasswordResetConfirmView.as_view(success_url='password_reset_complete'),
         name='password_reset_confirm'),
    path('reset_password/complete/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

    path('settings/', views.settings, name='settings'),
    path('settings/account/', views.account_settings, name='account_settings'),
    path('settings/security/', views.security_settings, name='security_settings'),
]

damzi/urls.py
from django.urls import path
from . import views


app_name = 'damzi'

urlpatterns = [
	path('', views.index, name='index'),
	path('messages/get/', views.get_messages, name='get_messages'),
]

kitchen/urls.py
from django.urls import path
from django.contrib.auth.decorators import permission_required, login_required, user_passes_test
from . import views

app_name = 'kitchen'

urlpatterns = [
    path('', views.index, name='index'),
    path('departments/', views.list_departments, name='list_departments'),
    path('department/<uuid:department_id>/courses/', views.list_main_courses, name='list_main_courses'),
    path('department/course/<uuid:course_id>/topics/', views.list_topics, name='list_topics'),
    path('department/course/topic/<uuid:topic_id>/subtopics/', views.list_subtopics, name='list_subtopics'),
    path('department/course/topic/subtopic/<uuid:subtopic_id>/edit/content/', views.edit_subtopic_content, name='edit_subtopic_content'),
    path('department/course/topic/subtopic/<uuid:subtopic_id>/edit/info/', views.edit_subtopic_info, name='edit_subtopic_info'),

    path('department/<uuid:department_id>/courses/add/', views.add_main_course, name='add_main_course'),
    path('department/course/<uuid:course_id>/topics/add/', views.add_topic, name='add_topic'),
    path('department/course/topic/<uuid:topic_id>/subtopics/add/', views.add_subtopic, name='add_subtopic'),

    path('required/courses/add/', views.add_required_course, name='add_required_course'),
    
    path('required/courses/', views.list_required_courses, name='list_required_courses'),

]

library/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from .import views

app_name = 'library'

urlpatterns = [
    path('courses/', views.list_courses, name='list_courses'),
    path('course/<uuid:pk>/topics/', login_required(views.list_topics), name='list_topics'),
    path('course/topic/<uuid:pk>/sub-topics/', views.list_subtopics, name='list_subtopics'),
    path('course/topic/sub-topic/<uuid:pk>/content/', views.list_subtopic_content, name='list_subtopic_content'),
    path('topic/<uuid:pk>/', login_required(views.topic_detail), name='topic_detail'),
    path('course/selection/add/', views.add_course_selection, name='add_course_selection'),
    path('course/selection/remove/', views.remove_course_selection, name='remove_course_selection'),
    path('faq/', views.faq, name='faq'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),

    # special urlpatterns
    path('comment_app/load/<topic_id>/', views.load_comment_app, name='load_comment_app'),
]

kitchen/models.py
from django.db import models

# Create your models here.

kitchen/forms.py
from django import forms
from django.core.exceptions import ValidationError

from library.models import Course, SubTopic, Topic


class AddCourseForm(forms.ModelForm):
    class Meta:
        model = Course
        fields = (
            'name',
            'code',
        )


class AddTopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = (
            'course',
            'title',
            'prev',
        )
        widgets = {
            'course': forms.HiddenInput()
        }

    def clean(self):
        cleaned_data = super().clean()
        if cleaned_data['prev'] is None:
            try:
                Topic.objects.get(course=cleaned_data['course'], prev__isnull=True)
                raise ValidationError({'prev': 'A first topic already exists'})
            except Topic.DoesNotExist:
                pass


class AddSubTopicForm(forms.ModelForm):
    class Meta:
        model = SubTopic
        fields = (
            'topic',
            'title',
            'prev',
        )
        widgets = {
            'topic': forms.HiddenInput()
        }

    def clean(self):
        cleaned_data = super().clean()
        if cleaned_data['prev'] is None:
            try:
                SubTopic.objects.get(topic=cleaned_data['topic'], prev__isnull=True)
                raise ValidationError({'prev': 'A first sub-topic already exists'})
            except SubTopic.DoesNotExist:
                pass


class EditSubTopicInfoForm(AddSubTopicForm):
    class Meta:
        model = SubTopic
        fields = (
            'title',
        )


class EditSubTopicContentForm(forms.ModelForm):
    class Meta:
        model = SubTopic
        fields = (
            'temp_content',
        )

kitchen/views.py
from django.contrib.auth.decorators import login_required, user_passes_test
from django.shortcuts import get_object_or_404, redirect, render
from django.views.generic.edit import CreateView
from django.views.generic.base import TemplateView
from library.models import Course, Department, SubTopic, Topic

from .forms import AddCourseForm, AddTopicForm, AddSubTopicForm, EditSubTopicContentForm, EditSubTopicInfoForm


@user_passes_test(lambda u: u.is_staff)
@login_required
def index(request):
    template_name = 'kitchen/index.html'
    return render(request, template_name)


@user_passes_test(lambda u: u.is_staff)
@login_required
def list_departments(request):
    template_name = 'kitchen/list_departments.html'
    departments = Department.objects.all()
    context = {
        'departments': departments,
    }
    return render(request, template_name, context)


@user_passes_test(lambda u: u.is_staff)
@login_required
def list_required_courses(request):
    template_name = 'kitchen/list_required_courses.html'
    courses = Course.objects.filter(is_required=True)
    context = {
        'courses': courses,
    }
    return render(request, template_name, context)


@user_passes_test(lambda u: u.is_staff)
@login_required
def list_main_courses(request, department_id):
    template_name = 'kitchen/list_main_courses.html'
    department = get_object_or_404(Department, id=department_id)
    courses = Course.objects.filter(department=department)
    context = {
        'department': department,
        'courses': courses,
    }
    return render(request, template_name, context)


@user_passes_test(lambda u: u.is_staff)
@login_required
def list_topics(request, course_id):
    template_name = 'kitchen/list_topics.html'
    course = get_object_or_404(Course, id=course_id)
    topics = Topic.get_topics_as_list(course)
    context = {
        'course': course,
        'topics': topics,
    }
    return render(request, template_name, context)


@user_passes_test(lambda u: u.is_staff)
@login_required
def list_subtopics(request, topic_id):
    template_name = 'kitchen/list_subtopics.html'
    topic = get_object_or_404(Topic, id=topic_id)
    subtopics = SubTopic.get_subtopics_as_list(topic)
    context = {
        'topic': topic,
        'subtopics': subtopics,
    }
    return render(request, template_name, context)


@user_passes_test(lambda u: u.is_staff)
@login_required
def edit_subtopic_content(request, subtopic_id):
    template_name = 'kitchen/edit_subtopic_content.html'
    form = EditSubTopicContentForm
    subtopic = get_object_or_404(SubTopic, id=subtopic_id)
    if request.method == 'POST':
        form = form(data=request.POST, instance=subtopic)
        if form.is_valid():
            form.save()
            return redirect('kitchen:edit_subtopic_content', subtopic_id=subtopic.id)
        else:
            context = {
                'subtopic': subtopic,
                'form': form,
            }
            return render(request, template_name, context)
    else:
        form = form(instance=subtopic)
        context = {
            'subtopic': subtopic,
            'form': form,
        }
        return render(request, template_name, context)


@user_passes_test(lambda u: u.is_staff)
@login_required
def edit_subtopic_info(request, subtopic_id):
    template_name = 'kitchen/edit_subtopic_info.html'
    form = EditSubTopicInfoForm
    subtopic = get_object_or_404(SubTopic, id=subtopic_id)
    if request.method == 'POST':
        form = form(data=request.POST, instance=subtopic)
        if form.is_valid():
            form.save()
            return redirect('kitchen:edit_subtopic_content', subtopic_id=subtopic.id)
    else:
        form = form(instance=subtopic)
        context = {
            'form': form,
        }
        return render(request, template_name, context)


@user_passes_test(lambda u: u.is_staff)
@login_required
def add_main_course(request, department_id):
    template_name = 'kitchen/add_main_course.html'
    form = AddCourseForm
    department = get_object_or_404(Department, id=department_id)
    if request.method == 'POST':
        form = form(data=request.POST)
        if form.is_valid():
            new_course = form.save(commit=False)
            new_course.department = department
            new_course.save()
            return redirect('kitchen:list_main_courses', department_id=department_id)
    else:
        context = {
            'form': form
        }
        return render(request, template_name, context)


@user_passes_test(lambda u: u.is_staff)
@login_required
def add_required_course(request):
    template_name = 'kitchen/add_required_course.html'
    form = AddCourseForm
    if request.method == 'POST':
        form = form(data=request.POST)
        if form.is_valid():
            new_course = form.save(commit=False)
            new_course.is_required = True
            new_course.save()
            return redirect('kitchen:list_required_courses')
    else:
        context = {
            'form': form,
        }
        return render(request, template_name, context)


@user_passes_test(lambda u: u.is_staff)
@login_required
def add_topic(request, course_id):
    template_name = 'kitchen/add_topic.html'
    course = get_object_or_404(Course, id=course_id)
    if request.method == 'POST':
        form = AddTopicForm(data=request.POST, initial={'course': course})
        if form.is_valid():
            form.save()
            return redirect('kitchen:list_topics', course_id=course_id)
        else:
            return render(request, template_name, {'form': form})
    else:
        context = {
            'form': AddTopicForm(initial={'course': course})
        }
        return render(request, template_name, context)


@user_passes_test(lambda u: u.is_staff)
@login_required
def add_subtopic(request, topic_id):
    template_name = 'kitchen/add_subtopic.html'
    topic = get_object_or_404(Topic, id=topic_id)
    if request.method == 'POST':
        form = AddSubTopicForm(data=request.POST, initial={'topic': topic})
        if form.is_valid():
            form.save()
            return redirect('kitchen:list_subtopics', topic_id=topic_id)
        else:
            return render(request, template_name, {'form': form})
    else:
        context = {
            'form': AddSubTopicForm(initial={'topic': topic}),
        }
        return render(request, template_name, context)

kitchen/templates/kitchen/add_main_course.html
{% extends 'kitchen/base.html' %}

{% block body %}
<form action="" method="post">
    {% csrf_token %}
    {% for field in form %}
    <div>
        {{ field.label_tag }}
        {{ field }}
    </div>
    {% endfor %}
    <button type="submit">Add</button>
</form>
{% endblock %}

kitchen/templates/kitchen/add_required_course.html
{% extends 'kitchen/base.html' %}

{% block body %}
<form action="" method="post">
    {% csrf_token %}
    {% for field in form %}
    <div>
        {{ field.label_tag }}
        {{ field }}
    </div>
    {% endfor %}
    <button type="submit">Add</button>
</form>
{% endblock %}

kitchen/templates/kitchen/add_subtopic.html
{% extends 'kitchen/base.html' %}

{% block body %}
<form action="" method="post">
    {% csrf_token %}
    {% for field in form %}
    <div>
        {{ field.errors }}
        {{ field.label_tag }}
        {{ field }}
    </div>
    {% endfor %}
    <button type="submit">Add</button>
</form>
{% endblock %}

kitchen/templates/kitchen/add_topic.html
{% extends 'kitchen/base.html' %}

{% block body %}
<form action="" method="post">
    {% csrf_token %}
    {% for field in form %}
    <div>
        {{ field.errors }}
        {{ field.label_tag }}
        {{ field }}
    </div>
    {% endfor %}
    <button type="submit">Add</button>
</form>
{% endblock %}

kitchen/templates/kitchen/base.html
<!--loads the path to our static files -->
{% load static %}


<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-85689451-2"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-85689451-2');
</script>

    <meta name="google-site-verification" content="xSCoNEvMbZAmq4Kg8aalqJyQV1AY4Hc91jaCVV1VVgs" />
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0">
    <title>{% block title %}CP Control Panel{% endblock %}</title>

    <!--all the necessary files-->
    <!-- Page styles -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:regular,bold,italic,thin,light,bolditalic,black,medium&amp;lang=en">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <!--Material Design Font-->
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <!-- Material Design Bootstrap All CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'kitchen/css/bootstrap.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'kitchen/css/mdb.min.css' %}" />

    <!-- Material Design Lite -->
    <link rel="stylesheet" href="{% static 'kitchen/mdl/material.min.css' %}">


    <!-- Damzinium Custom CSS -->
    <!--the core features of the page... navbar, footer-->
    <link rel="stylesheet" type="text/css" href="{% static 'kitchen/css/default.css' %}">

    <!-- Styles for Utilities -->
    <link rel="stylesheet" type="text/css" href="{% static 'damzi/css/utils.css' %}">
    <!-- Styles for Utilities -->

    <style type="text/css">
        /* New features */
        .loader {
            position: fixed;
            left: 0;
            top: 0;
            z-index: 99;
            width: 100%;
            height: 100%;
            background: white;
            /*middle of page*/
            display: flex;
            justify-content: center;
            align-items: center;
            box-sizing: border-box;
        }

        .loader-text {
            font-size: 30px;
        }

        .loader-img {
            width: 40px;
        }
        /* New features */
    </style>
<script src=" {% static  'kitchen/js/ckeditor/ckeditor.js' %}"></script>

</head>
<body class="hidden-sn">
    <!-- New features -->
    <div class="loader">
        <img class="loader-img" src="{% static 'damzi/img/loading.gif' %}" alt="loading"/>
        <div class="loader-text">
            Damzinium
        </div>
    </div>
    <!-- New features -->
<div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">

        <!--NAVBAR-->
      <div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">

      <div class="android-header mdl-layout__header mdl-layout__header--waterfall damzinium-green-head">
        <div class="mdl-layout__header-row">
          <span class="android-title mdl-layout-title">
            <!--navbar logo-->
            <img class="android-logo-image" src="{% static 'account/images/logoandtext.png' %}" style="height:100%;">
          </span>
          <!-- Add spacer, to align navigation to the right in desktop -->
          <div class="android-header-spacer mdl-layout-spacer"></div>
          <span class="android-mobile-title mdl-layout-title">
            <img class="android-logo-image" src="{% static 'account/images/logoandtext.png' %}" style="height:100%;">
          </span>
            <a class="mdl-navigation__link mdl-typography--text-uppercase" href="{% url 'accounts:profile' %}" style="color: #fff !important;">Home</a>
            <a class="mdl-navigation__link mdl-typography--text-uppercase" href="{% url 'library:list_courses' %}" style="color: #fff !important;">Courses</a>
            <a class="mdl-navigation__link mdl-typography--text-uppercase" href="{% url 'damzi:index' %}" style="color: #fff !important;">Sign Out</a>
        </div>
      </div>
        <!--END NAVBAR-->

    <!-- MAIN BODY -->
    <div class="mdl-layout__content">
        <!--WORK HERE-->
        {% block body %}
        {% endblock %}
        <!-- /WORK HERE -->


        <!--Footer-->
        <footer class="page-footer center-on-small-only damzinium-dark-foot">

            <!--Footer Links-->
            <div class="container">
                <div class="row my-4">

                    <!--First column-->
                    <div class="col-md-8 col-lg-8">
                        <h6 class="title mb-4 font-bold">Damzinium.com At A Glance</h6>
                        <p>We stand for smart and easy learning.</p>
                        <p>We give you quality and concise explanations of your course material.</p>
                        <p>You can trust us, we've got your back.</p>
                    </div>
                    <!--/.First column-->


                    <hr class="clearfix w-100 d-md-none">


                </div>
            </div>
            <!--/.Footer Links-->

            <!--Copyright-->
            <div class="footer-copyright">
                <div class="container-fluid">
                    2018. <a href="https://www.damzinium.com"> Damzinium.com </a> Learn Smart!

                </div>
            </div>
            <!--/.Copyright-->

        </footer>
        <!--/.Footer-->
      </div>
      <!-- /MAIN BODY -->
</div>
     <!-- New features -->
    <div class="network-status alert-info">
        <div>
            <img src="{% static 'damzi/img/offline.png' %}" alt="offline image"/>
            No internet connection
        </div>
    </div>
    <!-- New features -->
    <script type="text/javascript">
        // show page loading overlay
        window.addEventListener("load", function () {
            const loader = document.querySelector(".loader");
            loader.classList.add("hidden");
        });
    </script>
    <!-- Scripts for Utilities -->
    <script type="text/javascript" src="{% static 'damzi/js/utils.js' %}"></script>
    <!-- Scripts for Utilities -->
</body>
</html>

kitchen/templates/kitchen/edit_subtopic_content.html
{% extends 'kitchen/base.html' %}

{% block body %}
{{ form.media }}

<h1>{{ subtopic.topic.title }}</h1>
<h2>{{ subtopic.title }}</h2>
<a href="{% url 'kitchen:edit_subtopic_info' subtopic.id %}">Edit Info</a>
    <form action="" method="post">
        {% csrf_token %}
        <div>
            {{ form.temp_content.errors }}
            {{ form.temp_content.label_tag }}
            {{ form.temp_content }}
        </div>
        <button type="submit">Save</button>
    </form>
{% endblock %}

kitchen/templates/kitchen/edit_subtopic_info.html
{% extends 'kitchen/base.html' %}

{% block body %}

<form action="" method="post">
    {% csrf_token %}
    {% for field in form %}
    <div>
        {{ field.errors }}
        {{ field.label_tag }}
        {{ field }}
    </div>
    {% endfor %}
    <button type="submit">Save</button>
</form>
{% endblock %}

kitchen/templates/kitchen/form-template.html
<div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <div class="form-row">
			<div class="">
	        	<div class="">
				    {{ form.profile_picture.errors }}
				    <label> {{ form.profile_picture.label_tag }} </label>
				    {{ form.profile_picture }}
				</div>
			</div>
		</div>
        <div class="form-row">
        	<div class="">
	        	<div class="browser-default custom-select">
				    {{ form.institution.errors }}
				    <label class=""> {{ form.institution.label_tag }} </label>
				    {{ form.institution }}
				</div>
			</div>
		</div><br>
		<!-- <div class="form-row">
			<div class="col">
	        	<div class="">
				    {{ form.department_name.errors }}
				    <label> {{ form.department_name.label_tag }} </label>
				    {{ form.department_name }}
				</div>
			</div>
		</div> -->
		<div class="form-row">
        	<div class="">
	        	<div class="browser-default custom-select">
				    {{ form.level.errors }}
				    <label class=""> {{ form.level.label_tag }} </label>
				    {{ form.level }}
				</div>
			</div>
		</div><br>
		<div class="form-row">
			<div class="">
	        	<div class="">
				    {{ form.phone_number.errors }}
				    <input class="form-control" type="tel" id="phone_number" name="phone_number" placeholder="Your active phone number">
                    <label for="{{ form.phone_number.phone_number }}"></label>
		    	</div>
			</div>
		</div>
</div>

kitchen/templates/kitchen/index.html
{% extends 'kitchen/base.html' %}
{% load static %}

{% block body %}
<div>
	<a href="{% url 'kitchen:list_departments' %}">Departments</a>
</div>
<div>
	<a href="{% url 'kitchen:list_required_courses' %}">Required Courses</a>
</div>

{% endblock %}

kitchen/templates/kitchen/list_departments.html
{% extends 'kitchen/base.html' %}

{% block body %}

{% for department in departments %}
<a href="{% url 'kitchen:list_main_courses' department.id %}">{{ department.name }}</a>
{% endfor %}
{% endblock %}

kitchen/templates/kitchen/list_main_courses.html
{% extends 'kitchen/base.html' %}

{% block body %}

<small>
    <a href="{% url 'kitchen:add_main_course' department.id %}" class="">add</a>
</small>

{% for course in courses %}
<div>
    <a href="{% url 'kitchen:list_topics' course.id %}">{{ course.name }}</a>
</div>
{% endfor %}
{% endblock %}

kitchen/templates/kitchen/list_required_courses.html
{% extends 'kitchen/base.html' %}

{% block body %}

<small>
    <a href="{% url 'kitchen:add_required_course' %}">add</a>
</small>

{% for course in courses %}
<div>
    <a href="{% url 'kitchen:list_topics' course.id %}">{{ course.name }}</a>
</div>
{% endfor %}
{% endblock %}

kitchen/templates/kitchen/list_subtopics.html
{% extends 'kitchen/base.html' %}

{% block body %}

<small>
    <a href="{% url 'kitchen:add_subtopic' topic.id %}">add</a>
</small>
{% for subtopic in subtopics %}
<div>
    <a href="{% url 'kitchen:edit_subtopic_content' subtopic.id %}">{{ subtopic.title }}</a>
</div>
{% endfor %}
{% endblock %}

kitchen/templates/kitchen/list_topics.html
{% extends 'kitchen/base.html' %}

{% block body %}

<small>
    <a href="{% url 'kitchen:add_topic' course.id %}">add</a>
</small>
{% for topic in topics %}
<div>
    <a href="{% url 'kitchen:list_subtopics' topic.id %}">{{ topic.title }}</a>
</div>
{% endfor %}
{% endblock %}