accounts/urls.py
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required
from django.urls import path

from . import views

app_name = 'accounts'

urlpatterns = [
    path('', login_required(views.home), name='profile'),
    # path('ots/', login_required(views.OtsView.as_view()), name='ots'),
    path('ots/', login_required(views.ots), name='ots'),
    path('register/', views.UserRegistrationView.as_view(), name='register'),

    # user auth urls
    path('login/', views.ac_login, name='login'),
    path('logout/', views.ac_logout, name='logout'),
    # path('auth/', views.auth_view, name='auth_view'),

    # # ugrc
    # path('topic/<int:pk>/', (views.UgrcTopicView.as_view()), name='ugrc_detail'),
    # path('content/<int:pk>/', (views.UgContent.as_view()), name='content'),

    # password reset
    path('reset_password/', auth_views.PasswordResetView.as_view(success_url='password_reset_done'), name='password_reset'),
    path('reset_password/password_reset_done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset_password/password_reset_confirm/<slug:uidb64>/<slug:token>',
         auth_views.PasswordResetConfirmView.as_view(success_url='password_reset_complete'),
         name='password_reset_confirm'),
    path('reset_password/complete/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

    path('settings/', views.settings, name='settings'),
    path('settings/account/', views.account_settings, name='account_settings'),
    path('settings/security/', views.security_settings, name='security_settings'),
]

damzi/urls.py
from django.urls import path
from . import views


app_name = 'damzi'

urlpatterns = [
	path('', views.index, name='index'),
	path('messages/get/', views.get_messages, name='get_messages'),
]

kitchen/urls.py
from django.urls import path
from django.contrib.auth.decorators import permission_required, login_required, user_passes_test
from . import views

app_name = 'kitchen'

urlpatterns = [
    path('', views.index, name='index'),
    path('departments/', views.list_departments, name='list_departments'),
    path('department/<uuid:department_id>/courses/', views.list_main_courses, name='list_main_courses'),
    path('department/course/<uuid:course_id>/topics/', views.list_topics, name='list_topics'),
    path('department/course/topic/<uuid:topic_id>/subtopics/', views.list_subtopics, name='list_subtopics'),
    path('department/course/topic/subtopic/<uuid:subtopic_id>/edit/content/', views.edit_subtopic_content, name='edit_subtopic_content'),
    path('department/course/topic/subtopic/<uuid:subtopic_id>/edit/info/', views.edit_subtopic_info, name='edit_subtopic_info'),

    path('department/<uuid:department_id>/courses/add/', views.add_main_course, name='add_main_course'),
    path('department/course/<uuid:course_id>/topics/add/', views.add_topic, name='add_topic'),
    path('department/course/topic/<uuid:topic_id>/subtopics/add/', views.add_subtopic, name='add_subtopic'),

    path('required/courses/add/', views.add_required_course, name='add_required_course'),
    
    path('required/courses/', views.list_required_courses, name='list_required_courses'),

]

library/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from .import views

app_name = 'library'

urlpatterns = [
    path('courses/', views.list_courses, name='list_courses'),
    path('course/<uuid:pk>/topics/', login_required(views.list_topics), name='list_topics'),
    path('course/topic/<uuid:pk>/sub-topics/', views.list_subtopics, name='list_subtopics'),
    path('course/topic/sub-topic/<uuid:pk>/content/', views.list_subtopic_content, name='list_subtopic_content'),
    path('topic/<uuid:pk>/', login_required(views.topic_detail), name='topic_detail'),
    path('course/selection/add/', views.add_course_selection, name='add_course_selection'),
    path('course/selection/remove/', views.remove_course_selection, name='remove_course_selection'),
    path('faq/', views.faq, name='faq'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),

    # special urlpatterns
    path('comment_app/load/<topic_id>/', views.load_comment_app, name='load_comment_app'),
]

library/models.py
import os
import uuid

from ckeditor_uploader.fields import RichTextUploadingField
from django.core.exceptions import ValidationError
from django.db import models
from django.dispatch import receiver
from django.utils import timezone


class Institution(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=100)

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return self.name


class School(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    institution = models.ForeignKey(Institution, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return self.name


class Department(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    school = models.ForeignKey(School, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return self.name


class Course(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    institution = models.ForeignKey(Institution, null=True, on_delete=models.CASCADE, editable=False)
    department = models.ForeignKey(Department, blank=True, null=True, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    code = models.CharField(max_length=100)
    is_required = models.BooleanField(default=False, editable=False)

    def save(self, *args, **kwargs):
        if self.department is None:
            self.is_required = True
        super().save(*args, **kwargs)

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return self.code + ":" + self.name


class Topic(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)

    prev = models.OneToOneField('self', null=True, blank=True, verbose_name='previous topic',
                                on_delete=models.DO_NOTHING, related_name='next')



    @classmethod
    def get_topics_as_list(cls, course):
        try:
            first_topic = cls.objects.get(course=course, prev__isnull=True)
        except cls.DoesNotExist:
            return []
        topics = [first_topic]
        try:
            while topics[-1].next:
                topics.append(topics[-1].next)
        except Topic.next.RelatedObjectDoesNotExist:
            return topics

    def __str__(self):
        return self.title


class SubTopic(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    content = RichTextUploadingField(editable=False, null=True)
    temp_content = RichTextUploadingField(verbose_name='content')
    push_updates = models.BooleanField(default=False)

    prev = models.OneToOneField('self', null=True, blank=True, verbose_name='previous subtopic',
                                on_delete=models.DO_NOTHING, related_name='next')

    @classmethod
    def get_subtopics_as_list(cls, topic):
        try:
            first_subtopic = cls.objects.get(topic=topic, prev__isnull=True)
        except cls.DoesNotExist:
            return []
        subtopics = [first_subtopic]
        try:
            while subtopics[-1].next:
                subtopics.append(subtopics[-1].next)
        except cls.next.RelatedObjectDoesNotExist:
            return subtopics

    def __str__(self):
        return self.title


class Comment(models.Model):
    from accounts.models import User

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE, editable=False)
    commenter = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.TextField()
    date_uploaded = models.DateTimeField(editable=False, default=timezone.now)
    is_approved = models.BooleanField(verbose_name='check to approve', default=False)

    def __str__(self):
        return self.commenter.username


class Reply(models.Model):
    from accounts.models import User

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    comment = models.ForeignKey(
        Comment,
        on_delete=models.CASCADE,
        limit_choices_to={'is_approved': True}
    )
    replier = models.ForeignKey(User, on_delete=models.CASCADE)
    reply = models.TextField()
    date_uploaded = models.DateTimeField(editable=False, default=timezone.now)


class CourseSelection(models.Model):
    from accounts.models import User

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    semester = models.IntegerField(choices=((1, 2,),), default=os.environ.get('SEMESTER', 2))
    selection_date = models.DateTimeField(auto_now_add=True)


@receiver(models.signals.post_save, sender=SubTopic)
def push_updates(sender, instance, **kwargs):
    if instance.push_updates:
        instance.content = instance.temp_content
        instance.push_updates = False
        instance.save()

accounts/forms.py
from django import forms
from django.contrib.auth import authenticate
from django.core.exceptions import ValidationError

from .models import Profile, User
from .utils import is_phone_number


class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    confirm_password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = [
            'username',
            'first_name',
            'last_name',
            'email',
            'password',
            'confirm_password'
        ]

    def clean_first_name(self):
        return self.cleaned_data['first_name'].upper()

    def clean_last_name(self):
        return self.cleaned_data['last_name'].upper()


class ProfileForm(forms.ModelForm):
    phone_number = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control-text',
    }), help_text='Enter your phone number. eg: 0272727388')

    # date_of_birth = forms.DateField(widget=forms.SelectDateWidget(
    #     years=generate_years_for_bday(),
    # ))

    def clean_phone_number(self):
        phone_number = self.cleaned_data['phone_number']
        if not is_phone_number(phone_number):
            raise ValidationError('Please enter a valid number. eg: 0242425222.')
        return phone_number

    class Meta:
        model = Profile
        fields = [
            'profile_picture',
            'institution',
            # 'department',
            'level',
            'phone_number',
            # 'date_of_birth'
        ]

    def save(self, commit=True):
        user = super(ProfileForm, self).save(commit=False)

        if commit:
            user.save()

        return user


class UserLoginForm(forms.Form):
    username_or_email = forms.CharField(max_length=255, widget=forms.TextInput(
        attrs={
            'placeholder': 'Email or Username',
            'class': 'form-control',
            'autocomplete': 'off',
            'onkeyup': 'loginBtnStateHandler()',
            'onchange': 'loginBtnStateHandler()'
        })
    )
    password = forms.CharField(max_length=255, widget=forms.PasswordInput(
        attrs={
            'placeholder': 'Password',
            'class': 'form-control',
            'onkeyup': 'loginBtnStateHandler()',
            'onchange': 'loginBtnStateHandler()'
        }
    ))

    def clean(self):
        cleaned_data = super().clean()

        username_or_email = cleaned_data.get('username_or_email')
        password = cleaned_data.get('password')

        user = authenticate(username=username_or_email, password=password)
        if user is None:
            try:
                username = User.objects.get(email=username_or_email).username
                user = authenticate(username=username, password=password)
            except User.DoesNotExist:
                user = None
                raise ValidationError('Incorrect username or email or password.')
        if user is not None:
            self.user = user
            return self
        else:
            raise ValidationError('Incorrect username or email or password.')


class NamesUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name')
        widgets = {
            'first_name': forms.TextInput(attrs={
                'class': 'form-control',
                'autocomplete': 'off',
            }),
            'last_name': forms.TextInput(attrs={
                'class': 'form-control',
                'autocomplete': 'off',
            })
        }


class EmailUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('email', )
        widgets = {
            'email': forms.EmailInput(attrs={
                'class': 'form-control',
                'autocomplete': 'off',
            })
        }


class InstitutionUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('institution', )
        widgets = {
            'institution': forms.Select(attrs={
                'class': 'form-control',
            })
        }


class DepartmentUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('department', )
        widgets = {
            'department': forms.Select(attrs={
                'class': 'form-control',
            })
        }


class LevelUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('level', )


class PhoneNumberUpdateForm(forms.ModelForm):
    def clean_phone_number(self):
        phone_number = self.cleaned_data['phone_number']
        if not is_phone_number(phone_number):
            raise ValidationError('Please enter a valid number. eg: 0242425222.')
        return phone_number

    class Meta:
        model = Profile
        fields = ('phone_number', )
        widgets = {
            'phone_number': forms.TextInput(attrs={
                'class': 'form-control',
                'autocomplete': 'off',
            })
        }


class ProfilePictureUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('profile_picture', )
        widget = {
            'profile_picture': forms.ClearableFileInput(attrs={
                'class': 'form-control',
            })
        }


class AccountSettingsForm(forms.ModelForm):
    class Meta:
        model = User
        fields = (
            'first_name',
            'last_name',
        )


class ProfileSettingsForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = (
            'profile_picture',
            'institution',
            'phone_number',
        )


class ChangePasswordform(forms.Form):
    current_password = forms.CharField(widget=forms.PasswordInput)
    new_password = forms.CharField(widget=forms.PasswordInput)
    confirm_new_password = forms.CharField(widget=forms.PasswordInput)

accounts/templates/accounts/error_page.html
<p>
	<em>
		<h1>
			No such page exists
		</h1>
	</em>
</p>

accounts/templates/accounts/footer.html
{% load static %}
<footer class="page-footer center-on-small-only damzinium-dark-foot">
    <div class="container">
        <div class="row my-4">
            <div class="col-md-4 col-lg-4"><!--First column-->
                <h6 class="title mb-4 font-bold">Damzinium.com At A Glance</h6>
                <p>We stand for smart and easy learning.</p>
                <p>We give you quality and concise explanations of your course materials</p>
                <p>You can trust us, we've got your back.</p>
            </div>
            <!--/.First column-->
            <hr class="clearfix w-100 d-md-none">
            <!--Second column-->
            <div class="col-md-2 col-lg-2 ml-auto">
                <h6 class="title mb-4 font-bold">Quick Links</h6>
                <ul>
                    <p><a href="{% url 'accounts:profile' %}">Home</a></p>
                    <p><a href="{% url 'library:list_courses' %}">Courses</a></p>
                    <p><a href="{% url 'library:about' %}">About</a></p>
                    <p><a href="{% url 'library:contact' %}">Contact</a></p>
                    <p><a href="{% url 'library:faq' %}">FAQ</a></p> 
                </ul>
            </div>
            <!--/.Second column-->
            <hr class="clearfix w-100 d-md-none">
            <!--Third column-->
            <div class="col-md-4 col-lg-3">
                <h6 class="mb-4"></h6>
                        <!-- clock widget start -->
                        <script type="text/javascript"> var css_file=document.createElement("link"); css_file.setAttribute("rel","stylesheet"); css_file.setAttribute("type","text/css"); css_file.setAttribute("href","//s.bookcdn.com//css/cl/bw-cl-150x100t.css"); document.getElementsByTagName("head")[0].appendChild(css_file); </script> <div id="tw_8_780729980"><div style="width:150px; height:100px; margin: 0 auto;"><a href="http://booked.net/time/accra-7506">Accra</a><br/></div></div> <script type="text/javascript"> function setWidgetData_780729980(data){ if(typeof(data) != 'undefined' && data.results.length > 0) { for(var i = 0; i < data.results.length; ++i) { var objMainBlock = ''; var params = data.results[i]; objMainBlock = document.getElementById('tw_'+params.widget_type+'_'+params.widget_id); if(objMainBlock !== null) objMainBlock.innerHTML = params.html_code; } } } var clock_timer_780729980 = -1; </script> <script type="text/javascript" charset="UTF-8" src="https://widgets.booked.net/time/info?ver=2&domid=209&type=8&id=780729980&scode=124&city_id=7506&wlangid=1&mode=1&details=0&background=rgba(0,0,0,0.6)&color=ffffff&add_background=ffffff&add_color=ffffff&head_color=ffffff&border=0&transparent=1"></script>
                        <!-- clock widget end -->
            </div>
            <!--/.Third column-->
            <hr class="clearfix w-100 d-md-none">
            <!--Fourth column-->
            <div class="col-md-2 col-lg-2 text-center">
                <h6 class="title mb-4 font-bold">Follow Us</h6>
                <!--Social buttons-->
                <div class="social-section mt-2 ">
    <!--Facebook--> <a type="button" href="https://web.facebook.com/Damzinium-INC-285192118553538/" class="btn-floating btn-small btn-fb"><i class="fab fa-facebook"></i></a>
    <!--Twitter-->  <a type="button" href="https://twitter.com/damzinium_inc" class="btn-floating btn-small btn-tw"><i class="fab fa-twitter"></i></a>
    <!--Google +--> <a type="button" href="https://plus.google.com/u/0/103145716500637224815" class="btn-floating btn-small btn-gplus"><i class="fab fa-google-plus-g"></i></a>
    <!--Instagram--><a type="button" href="https://www.instagram.com/damzinium_inc/" class="btn-floating btn-small btn-dribbble"><i class="fab fa-instagram"></i></a>
                </div>
            </div>
        </div>
    </div>
 <!--Copyright--><div class="footer-copyright"><div class="container-fluid">2019. <a href="https://www.damzinium.com">Damzinium.com </a> Learn Smart!</div>
    </div><!--/.Copyright-->
</footer><!--/.Footer-->

accounts/templates/accounts/header.html
{% load static %}

<!--NAVBAR-->
      <div class="android-header mdl-layout__header mdl-layout__header--waterfall  gradient-nav" style="color: #fff !important;">
        <div class="mdl-layout__header-row">
          <span class="android-title mdl-layout-title">
            <!--navbar logo-->
            <img class="android-logo-image" src="{% static 'account/images/logoandtext.png' %}" style="height:100%;">
          </span>
          <!-- Add spacer, to align navigation to the right in desktop -->
          <div class="android-header-spacer mdl-layout-spacer"></div>
          <div class="android-search-box mdl-textfield mdl-js-textfield mdl-textfield--expandable mdl-textfield--floating-label mdl-textfield--align-right mdl-textfield--full-width">
            <label class="mdl-button mdl-js-button mdl-button--icon" for="search-field">
              <i class="material-icons" style="margin-top: 10px; color: #fff !important;">search</i>
            </label>
            <div class="mdl-textfield__expandable-holder">
              <input class="mdl-textfield__input" type="text" id="search-field">
            </div>
          </div>
          <!-- Navigation -->
          <div class="android-navigation-container" style="text-decoration-color: #fff !important;">
            <nav class="android-navigation mdl-navigation" style="color: #fff !important;">
                <a class="mdl-navigation__link mdl-typography--text-uppercase" href="{% url 'accounts:profile' %}" style="color: #fff !important;">Home</a>
              <a class="mdl-navigation__link mdl-typography--text-uppercase" href="{% url 'library:list_courses' %}" style="color: #fff !important;">Courses</a>
              <a class="mdl-navigation__link mdl-typography--text-uppercase" href="{% url 'library:about' %}" style="color: #fff !important;">About</a>
              <a class="mdl-navigation__link mdl-typography--text-uppercase" href="{% url 'library:contact' %}" style="color: #fff !important;">Contact</a>
              <a class="mdl-navigation__link mdl-typography--text-uppercase" href="{% url 'library:faq' %}" style="color: #fff !important;">FAQ</a>
              {% if user.is_staff %}
                <a class="mdl-navigation__link mdl-typography--text-uppercase" href="{% url 'kitchen:index' %}" style="color: #fff !important;">Kitchen</a>
              {% endif %}
            </nav>
          </div>
          <span class="android-mobile-title mdl-layout-title">
            <img class="android-logo-image" src="{% static 'account/images/logoandtext.png' %}" style="height:100%;">
          </span>
          <button class="android-more-button mdl-button mdl-js-button mdl-button--icon mdl-js-ripple-effect" id="more-button">
            <i class="material-icons" style="color: #fff !important;">more_vert</i>
          </button>
          <ul class="mdl-menu mdl-js-menu mdl-menu--bottom-right mdl-js-ripple-effect" for="more-button">
              <a href="{% url 'accounts:logout' %}"><li class="mdl-menu__item">Sign out</li></a>
              <a href="{% url 'accounts:settings' %}"><li class="mdl-menu__item">Settings</li></a>
          </ul>
        </div>
      </div>
        <!--END NAVBAR-->

        <!-- SIDEBAR -->
      <div class="demo-drawer mdl-layout__drawer gradient-nav mdl-color-text--blue-grey-50">
        <header class="demo-drawer-header">
          <img src="{% static 'account/images/default.jpg' %}" class="demo-avatar">
          <div class="demo-avatar-dropdown">
            <span>{{ user.get_username }}</span>
            <div class="mdl-layout-spacer"></div>
            <button id="accbtn" class="mdl-button mdl-js-button mdl-js-ripple-effect mdl-button--icon">
              <i class="material-icons" role="presentation">arrow_drop_down</i>
              <span class="visuallyhidden">Accounts</span>
            </button>
            <ul class="mdl-menu mdl-menu--bottom-right mdl-js-menu mdl-js-ripple-effect" for="accbtn">
                <a href="{% url 'accounts:settings' %}"><li class="mdl-menu__item">Settings</li></a>
                <a href="{% url 'accounts:logout' %}"> <li class="mdl-menu__item">Sign out</li></a>
            </ul>
          </div>
        </header>
        <nav class="demo-navigation mdl-navigation stylish-color-dark">
          <a class="mdl-navigation__link mdl-color-text--blue-grey-100" href="{% url 'accounts:profile' %}"><i class="mdl-color-text--blue-grey-100 material-icons" role="presentation">home</i>Home</a>
          <a class="mdl-navigation__link mdl-color-text--blue-grey-100" href="{% url 'library:list_courses' %}"><i class="mdl-color-text--blue-grey-100 material-icons" role="presentation">library_books</i>Courses</a>
          <a class="mdl-navigation__link mdl-color-text--blue-grey-100" href="{% url 'library:about' %}"><i class="mdl-color-text--blue-grey-100 material-icons" role="presentation">info</i>About</a>
          <a class="mdl-navigation__link mdl-color-text--blue-grey-100" href="{% url 'library:contact' %}"><i class="mdl-color-text--blue-grey-100 material-icons" role="presentation">phone</i>Contact Us</a>

          <div class="mdl-layout-spacer"></div>

          <a class="mdl-navigation__link mdl-color-text--blue-grey-100" href="{% url 'library:faq' %}"><i class="mdl-color-text--blue-grey-100 material-icons" role="presentation">help_outline</i><span class="visuallyhidden">Help</span>FAQ</a>
        </nav>
      </div>
      <!-- END SIDEBAR -->

accounts/templates/accounts/profile.html
{% extends 'library/base.html' %} {% load static %} {% load ads_tags %} {% block title %}Home{% endblock %} 

{% block content %}
<style type="text/css">
  h5 {
    letter-spacing: 2px;
    margin: 0px;
  }
  
  @media (max-width: 768px) {
    .text-topic {
      width: 100%;
      text-align: justify;
      margin: auto;
    }
    .text-detail {
      width: 100%;
      text-align: justify;
      margin: auto;
    }
  }
  /*768px*/
  
  @media (min-width: 992px) {
    .text-topic {
      width: 30%;
      float: left
    }
    .text-detail {
      width: 70%;
      float: right;
      text-align: justify;
    }
  }
</style>

<section>
  <!-- Jumbotron -->
  <div class="card card-image gradient-nav">
    <div class="text-white text-center rgba-stylish-strong py-5 px-4">
      <div class="py-5">

        <!-- Content -->
        <i class="fas fa-graduation-cap fa-5x"></i>
        <h2 class="card-title h2 my-4 py-2"><strong>Welcome to the new learning experience.</strong></h2>
        <p class="mb-4 pb-2 px-md-5 mx-md-5">Over the past 3 years we have been hard at work, doing what we can to deliver to students the best learning experience
          possible. We are getting ever closer to our goal of delivering personalised learning to every student.</p>
        <a href="{% url 'library:about' %}" class="btn gradient-nav"><i class="fas fa-clone left"></i>Read more</a>

      </div>
    </div>
  </div>
  <!-- Jumbotron -->
</section>

<br>
<div class="container-fluid">
  {% comment %}
  <!-- advertisement 1 -->
  <div>
    <p class="text-center txt-ad-1"><a href="#">Vote for IA for UGSRC President 2019.</a></p>
    {% render_ads_zone 'sidebar' %}
  </div>
  <!-- advertisement 1 -->
  <br>
  {% endcomment %}
  <br>
  <section class="my-courses">
      <!-- container -->
    <div class="container">
        <h5 class="my-4">MY COURSES ({{ selected_courses|length}})</h5>
      <div class="swiper-container">
        <!-- .swiper-container -->
        <div class="swiper-wrapper my-2">

          <!-- if count > 0, show selected courses. else ask them to add a new course-->

          {% if selected_courses|length > 0 %}
            {% for course in selected_courses %}
            <div class="swiper-slide">
              <div class="mdl-card mdl-shadow--4dp" id="course-{{ course.id }}" style="width: 240px !important;">
                <div class="mdl-card__media"><img src="{% static 'account/images/placeholder.jpg' %}" width="100%" alt=""></div>
                <div class="mdl-card__title">{{ course.code }}</div>
                <div class="mdl-card__supporting-text">{{ course.name }}</div>
                <div class="mdl-card__actions mdl-card--border">
                  <a href="{% url 'library:list_topics' course.id %}" class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect">Study</a>
                  <a href="#" class="btn-floating btn-sm remove-course-selection-btn" style="position: absolute; top: 0; right: 0;"
                    id="{{ course.id }}"><i class="fa fa-trash"></i>
                  </a>
                </div>
              </div>
            </div>
            {% endfor %} 
          {% else %}
            <h5>You haven't selected any courses yet. <a href="{% url 'library:list_courses' %}">Add one.</a></h5>
          {% endif %}

        </div>

        <!-- If the number of selected courses is less than 4, then no need for the arrows-->
        {% if selected_courses|length > 4 %}
        <div class="swiper-button-next"></div>
        <div class="swiper-button-prev"></div>
        {% else %}
        {% endif %}
      </div>
      <!-- /.swiper-container -->
    </div>
    <!-- /.container -->

  </section>
  <br>
  {% comment %}
  <br>
  <!-- advertisement 2 -->
  <div>
    <p class="text-center txt-ad-2"><a href="#">Vote for IA for UGSRC President 2019.</a></p>
  </div>
  <!-- advertisement 2 -->
  {% endcomment %}
</div>
<!-- /.container-fluid -->


<script>
  $('.remove-course-selection-btn').click(
    function (e) {
      e.preventDefault();
      const csrf = $('{% csrf_token %}');
      $.post("{% url 'library:remove_course_selection' %}", {
        course_id: this.id,
        csrfmiddlewaretoken: csrf.val(),
      }, function (data) {
        const courseCard = $('#course-' + data.course_id)
        courseCard.fadeOut("slow", function () {
          courseCard.remove();
        });
        getAndRenderMessages();
      });
    }
  );

</script>

{% endblock %}

accounts/templates/accounts/security_settings.html
<h1>Hello World !!!</h1>